extends:
  - stylelint-config-html/vue
  - stylelint-config-standard
  - stylelint-config-recommended-scss
  - stylelint-config-recommended-vue
plugins:
  - stylelint-prettier
rules:
  prettier/prettier: true
